name: test
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['^1.12', '^1.13', '^1.14']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Build
        run: go build -ldflags="-s -w" ./cmd/getlocale
      - name: Set locale
        if: startsWith(matrix.os, 'macos')
        # Manually set the AppleLanguages on macOS
        # Otherwise, we get the following error when running GetLocales():
        # The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist
        run: defaults write NSGlobalDomain AppleLanguages "(en-US, fr-FR, ja-JP)"
      - name: Test
        run: go test -v -race
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/bin v1.24.0
      - name: Run golangci-lint
        run: ~/bin/golangci-lint run
